
site: &site
  name: Android Frontier
  url: http://android-frontier.org
  maven_repository_url: http://android-frontier.org/artifacts

development:
  secret_key_base: 0cb726c78be54356748181363256eaff0b4ec2d111cebca108f47cb832c3ae0ec25fe377b86908628601f7f5e63586d169491721fc6afd10f040041e8619c396
  artifact_root_path:  <%= ENV["ARTIFACT_ROOT_PATH"] %>
  site: *site

test:
  secret_key_base: 2e357d8a45436c86bb499e42a2da7d72c5f46af67a330d3a1943ea923dd5092e5d465eab0d8e96323e54ee366e900777233b9d24f053de01358621d36a6f5c03
  artifact_root_path: tmp/test/
  site: *site


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  x_sendfile_header:  <%= ENV["X_SENDFILE_HEADER"] %>
  artifact_root_path:  <%= ENV["ARTIFACT_ROOT_PATH"] %>
  site: *site
